package generator

import (
	"strings"
	"testing"

	"github.com/pangobit/go-wrangler/internal/parse"
)

func TestGenerateBindFunction(t *testing.T) {
	structInfo := parse.StructInfo{
		Name: "User",
		Tags: []parse.TagInfo{
			{
				FieldName: "Name",
				FieldType: "string",
				Bind: &parse.BindTag{
					Type:     "header",
					Required: true,
				},
			},
			{
				FieldName: "Email",
				FieldType: "string",
				Bind: &parse.BindTag{
					Type:     "query",
					Required: false,
				},
			},
			{
				FieldName: "Password",
				FieldType: "string",
				Bind: &parse.BindTag{
					Type:     "form",
					Required: true,
				},
			},
			{
				FieldName: "Age",
				FieldType: "int",
				Validate: &parse.ValidateTag{
					Min: &[]int{18}[0],
					Max: &[]int{120}[0],
				},
			},
		},
	}

	bindCode, _ := GenerateBindFunction(structInfo)
	validateCode, _ := GenerateValidateFunction(structInfo)
	result := bindCode + validateCode

	expected := `// Code generated by go-wrangler. DO NOT EDIT.

func BindUser(r *http.Request, s *User) error {
	r.ParseMultipartForm(32 << 20)
	s.Name = r.Header.Get("Name")
	if s.Name == "" {
		return fmt.Errorf("Name is required")
	}
	s.Email = r.URL.Query().Get("Email")
	s.Password = r.Form.Get("Password")
	if s.Password == "" {
		return fmt.Errorf("Password is required")
	}
	return nil
}
// Code generated by go-wrangler. DO NOT EDIT.

func ValidateUser(s *User) error {
	if s.Age < 18 {
		return fmt.Errorf("Age must be at least 18")
	}
	if s.Age > 120 {
		return fmt.Errorf("Age must be at most 120")
	}
	return nil
}
`

	if result != expected {
		t.Errorf("GenerateBindFunction() = %v, want %v", result, expected)
	}
}

func TestGenerateFormWithValidation(t *testing.T) {
	structInfo := parse.StructInfo{
		Name: "User",
		Tags: []parse.TagInfo{
			{
				FieldName: "Age",
				FieldType: "int",
				Bind: &parse.BindTag{
					Type:     "form",
					Required: true,
				},
				Validate: &parse.ValidateTag{
					Min: &[]int{18}[0],
					Max: &[]int{120}[0],
				},
			},
		},
	}

	bindCode, _ := GenerateBindFunction(structInfo)
	validateCode, _ := GenerateValidateFunction(structInfo)
	result := bindCode + validateCode

	expected := `// Code generated by go-wrangler. DO NOT EDIT.

func BindUser(r *http.Request, s *User) error {
	r.ParseMultipartForm(32 << 20)
	if val := r.Form.Get("Age"); val != "" {
		if val, err := strconv.Atoi(val); err != nil {
			return fmt.Errorf("Age must be a valid integer")
		} else {
			s.Age = val
		}
	}
	if r.Form.Get("Age") == "" {
		return fmt.Errorf("Age is required")
	}
	return nil
}
// Code generated by go-wrangler. DO NOT EDIT.

func ValidateUser(s *User) error {
	if s.Age < 18 {
		return fmt.Errorf("Age must be at least 18")
	}
	if s.Age > 120 {
		return fmt.Errorf("Age must be at most 120")
	}
	return nil
}
`

	if result != expected {
		t.Errorf("TestGenerateFormWithValidation() = %v, want %v", result, expected)
	}
}

func TestGenerateFloat64Binding(t *testing.T) {
	structInfo := parse.StructInfo{
		Name: "Modifier",
		Tags: []parse.TagInfo{
			{
				FieldName: "Name",
				FieldType: "string",
				Bind: &parse.BindTag{
					Type:     "form",
					Required: true,
				},
			},
			{
				FieldName: "Value",
				FieldType: "float64",
				Bind: &parse.BindTag{
					Type:     "form",
					Required: true,
				},
			},
		},
	}

	bindCode, imports := GenerateBindFunction(structInfo)

	expected := `// Code generated by go-wrangler. DO NOT EDIT.

func BindModifier(r *http.Request, s *Modifier) error {
	r.ParseMultipartForm(32 << 20)
	s.Name = r.Form.Get("Name")
	if s.Name == "" {
		return fmt.Errorf("Name is required")
	}
	if val := r.Form.Get("Value"); val != "" {
		if val, err := strconv.ParseFloat(val, 64); err != nil {
			return fmt.Errorf("Value must be a valid number")
		} else {
			s.Value = val
		}
	}
	if r.Form.Get("Value") == "" {
		return fmt.Errorf("Value is required")
	}
	return nil
}
`

	if bindCode != expected {
		t.Errorf("TestGenerateFloat64Binding() = %v, want %v", bindCode, expected)
	}

	hasStrconv := false
	for _, imp := range imports {
		if imp == "strconv" {
			hasStrconv = true
		}
	}
	if !hasStrconv {
		t.Errorf("Expected strconv import for float64 binding")
	}
}

func TestGeneratePackageSortsImportsDeterministically(t *testing.T) {
	structs := []parse.StructInfo{
		{
			Name: "User",
			Tags: []parse.TagInfo{
				{
					FieldName: "Name",
					FieldType: "string",
					Bind: &parse.BindTag{
						Type: "header",
					},
				},
			},
		},
		{
			Name: "Modifier",
			Tags: []parse.TagInfo{
				{
					FieldName: "Value",
					FieldType: "float64",
					Bind: &parse.BindTag{
						Type: "form",
					},
				},
			},
		},
	}

	code := GeneratePackage(structs, "generated")

	expectedImportBlock := "import (\n\t\"fmt\"\n\t\"net/http\"\n\t\"strconv\"\n)\n\n"
	if !strings.Contains(code, expectedImportBlock) {
		t.Fatalf("GeneratePackage() import block = %q, want ordered block %q", code, expectedImportBlock)
	}
}
