// Package generator provides functionality to generate Go code for struct binding and validation.
package generator

import (
	"fmt"
	"strings"

	"github.com/pangobit/go-wrangler/internal/parse"
)

// GenerateBindFunction generates a Go function that binds values from an http.Request to a struct based on its "bind" tags.
func GenerateBindFunction(structInfo parse.StructInfo) (string, []string) {
	var sb strings.Builder

	sb.WriteString("// Code generated by go-wrangler. DO NOT EDIT.\n\n")

	needsStrconv := false
	needsFormParse := false
	for _, tag := range structInfo.Tags {
		if tag.Bind != nil {
			if tag.FieldType == "int" || tag.FieldType == "[]int" {
				needsStrconv = true
			}
			if tag.Bind.Type == "form" {
				needsFormParse = true
			}
		}
	}

	imports := []string{"fmt", "net/http"}
	if needsStrconv {
		imports = append(imports, "strconv")
	}

	// Function signature
	sb.WriteString(fmt.Sprintf("func Bind%s(r *http.Request, s *%s) error {\n", structInfo.Name, structInfo.Name))

	if needsFormParse {
		sb.WriteString("\tif r.Form == nil {\n\t\tr.ParseMultipartForm(32 << 20)\n\t}\n")
	}

	// Bind logic
	for _, tag := range structInfo.Tags {
		if tag.Bind != nil {
			// Use custom name if provided, otherwise use field name
			lookupName := tag.FieldName
			if tag.Bind.Name != nil {
				lookupName = *tag.Bind.Name
			}

			valueExpr, ok := valueExpr(tag.Bind.Type, tag.FieldType, lookupName)
			if !ok {
				continue
			}

			isSlice := strings.HasPrefix(tag.FieldType, "[]")

			if tag.FieldType == "int" {
				sb.WriteString(fmt.Sprintf("\tif val, err := strconv.Atoi(%s); err != nil {\n\t\treturn fmt.Errorf(\"%s must be a valid integer\")\n\t} else {\n\t\ts.%s = val\n\t}\n", valueExpr, lookupName, tag.FieldName))
			} else if tag.FieldType == "[]int" {
				sb.WriteString(fmt.Sprintf("\t{\n\t\tvals := %s\n\t\ts.%s = make([]int, len(vals))\n\t\tfor i, v := range vals {\n\t\t\tif iv, err := strconv.Atoi(v); err != nil {\n\t\t\t\treturn fmt.Errorf(\"%s at index %%d must be a valid integer\", i)\n\t\t\t} else {\n\t\t\t\ts.%s[i] = iv\n\t\t\t}\n\t\t}\n\t}\n", valueExpr, tag.FieldName, lookupName, tag.FieldName))
			} else {
				sb.WriteString(fmt.Sprintf("\ts.%s = %s\n", tag.FieldName, valueExpr))
			}

			if tag.Bind.Required {
				if isSlice {
					sb.WriteString(fmt.Sprintf("\tif len(s.%s) == 0 {\n\t\treturn fmt.Errorf(\"%s is required\")\n\t}\n", tag.FieldName, lookupName))
				} else {
					// Use valueExpr for required check if it's a scalar from request
					checkExpr := valueExpr
					if tag.FieldType != "int" {
						checkExpr = "s." + tag.FieldName
					}
					sb.WriteString(fmt.Sprintf("\tif %s == \"\" {\n\t\treturn fmt.Errorf(\"%s is required\")\n\t}\n", checkExpr, lookupName))
				}
			}
		}
	}

	sb.WriteString("\treturn nil\n}\n")

	return sb.String(), imports
}

// GenerateValidateFunction generates a Go function that validates struct fields based on its "validate" tags.
func GenerateValidateFunction(structInfo parse.StructInfo) (string, []string) {
	var sb strings.Builder

	sb.WriteString("// Code generated by go-wrangler. DO NOT EDIT.\n\n")

	// Check if strconv is needed
	needsStrconv := false
	for _, tag := range structInfo.Tags {
		if tag.Validate != nil && tag.FieldType != "int" {
			needsStrconv = true
		}
	}

	imports := []string{"fmt"}
	if needsStrconv {
		imports = append(imports, "strconv")
	}

	// Function signature
	sb.WriteString(fmt.Sprintf("func Validate%s(s *%s) error {\n", structInfo.Name, structInfo.Name))

	// Validation logic
	for _, tag := range structInfo.Tags {
		if tag.Validate != nil {
			if tag.FieldType == "int" {
				if tag.Validate.Min != nil {
					sb.WriteString(fmt.Sprintf("\tif s.%s < %d {\n\t\treturn fmt.Errorf(\"%s must be at least %d\")\n\t}\n", tag.FieldName, *tag.Validate.Min, tag.FieldName, *tag.Validate.Min))
				}
				if tag.Validate.Max != nil {
					sb.WriteString(fmt.Sprintf("\tif s.%s > %d {\n\t\treturn fmt.Errorf(\"%s must be at most %d\")\n\t}\n", tag.FieldName, *tag.Validate.Max, tag.FieldName, *tag.Validate.Max))
				}
			} else {
				// For non-int, parse and check
				if tag.Validate.Min != nil {
					sb.WriteString(fmt.Sprintf("\tif val, err := strconv.Atoi(s.%s); err != nil {\n\t\treturn fmt.Errorf(\"%s must be a valid integer\")\n\t} else if val < %d {\n\t\treturn fmt.Errorf(\"%s must be at least %d\")\n\t}\n", tag.FieldName, tag.FieldName, *tag.Validate.Min, tag.FieldName, *tag.Validate.Min))
				}
				if tag.Validate.Max != nil {
					sb.WriteString(fmt.Sprintf("\tif val, err := strconv.Atoi(s.%s); err != nil {\n\t\treturn fmt.Errorf(\"%s must be a valid integer\")\n\t} else if val > %d {\n\t\treturn fmt.Errorf(\"%s must be at most %d\")\n\t}\n", tag.FieldName, tag.FieldName, *tag.Validate.Max, tag.FieldName, *tag.Validate.Max))
				}
			}
		}
	}

	sb.WriteString("\treturn nil\n}\n")

	return sb.String(), imports
}

// GeneratePackage generates a complete Go package containing binding and validation functions for multiple structs.
func GeneratePackage(structs []parse.StructInfo, pkgName string) string {
	var sb strings.Builder
	sb.WriteString("package " + pkgName + "\n\n")

	importSet := make(map[string]bool)
	var functions []string

	for _, s := range structs {
		bindCode, bindImports := GenerateBindFunction(s)
		functions = append(functions, bindCode)
		for _, imp := range bindImports {
			importSet[imp] = true
		}

		validateCode, validateImports := GenerateValidateFunction(s)
		functions = append(functions, validateCode)
		for _, imp := range validateImports {
			importSet[imp] = true
		}
	}

	if len(importSet) > 0 {
		sb.WriteString("import (\n")
		for imp := range importSet {
			sb.WriteString("\t\"" + imp + "\"\n")
		}
		sb.WriteString(")\n\n")
	}

	for _, fn := range functions {
		sb.WriteString(fn)
		sb.WriteString("\n")
	}

	return sb.String()
}

// valueExpr returns the Go code snippet for extracting a value from the request.
// It returns the expression and a boolean indicating if the source/type combination is supported.
func valueExpr(source, fieldType, key string) (string, bool) {
	isSlice := strings.HasPrefix(fieldType, "[]")

	switch source {
	case "query":
		if isSlice {
			return fmt.Sprintf("r.URL.Query()[\"%s\"]", key), true
		}
		return fmt.Sprintf("r.URL.Query().Get(\"%s\")", key), true
	case "header":
		if isSlice {
			return fmt.Sprintf("r.Header.Values(\"%s\")", key), true
		}
		return fmt.Sprintf("r.Header.Get(\"%s\")", key), true
	case "form":
		if isSlice {
			return fmt.Sprintf("r.Form[\"%s\"]", key), true
		}
		return fmt.Sprintf("r.FormValue(\"%s\")", key), true
	case "path":
		if isSlice {
			return "", false // Not natively supported
		}
		return fmt.Sprintf("r.PathValue(\"%s\")", key), true
	default:
		return "", false
	}
}
