package generator

import (
	"testing"

	"github.com/pangobit/go-wrangler/internal/parse"
)

func TestGenerateBindFunction(t *testing.T) {
	structInfo := parse.StructInfo{
		Name: "User",
		Tags: []parse.TagInfo{
			{
				FieldName: "Name",
				FieldType: "string",
				Bind: &parse.BindTag{
					Type:     "header",
					Required: true,
				},
			},
			{
				FieldName: "Email",
				FieldType: "string",
				Bind: &parse.BindTag{
					Type:     "query",
					Required: false,
				},
			},
			{
				FieldName: "Password",
				FieldType: "string",
				Bind: &parse.BindTag{
					Type:     "form",
					Required: true,
				},
			},
			{
				FieldName: "Age",
				FieldType: "int",
				Validate: &parse.ValidateTag{
					Min: &[]int{18}[0],
					Max: &[]int{120}[0],
				},
			},
		},
	}

	bindCode, _ := GenerateBindFunction(structInfo)
	validateCode, _ := GenerateValidateFunction(structInfo)
	result := bindCode + validateCode

	expected := `// Code generated by go-wrangler. DO NOT EDIT.

func BindUser(r *http.Request, s *User) error {
	s.Name = r.Header.Get("Name")
	if s.Name == "" {
		return fmt.Errorf("Name is required")
	}
	s.Email = r.URL.Query().Get("Email")
	s.Password = r.FormValue("Password")
	if s.Password == "" {
		return fmt.Errorf("Password is required")
	}
	return nil
}
// Code generated by go-wrangler. DO NOT EDIT.

func ValidateUser(s *User) error {
	if s.Age < 18 {
		return fmt.Errorf("Age must be at least 18")
	}
	if s.Age > 120 {
		return fmt.Errorf("Age must be at most 120")
	}
	return nil
}
`

	if result != expected {
		t.Errorf("GenerateBindFunction() = %v, want %v", result, expected)
	}
}

func TestGenerateFormWithValidation(t *testing.T) {
	structInfo := parse.StructInfo{
		Name: "User",
		Tags: []parse.TagInfo{
			{
				FieldName: "Age",
				FieldType: "int",
				Bind: &parse.BindTag{
					Type:     "form",
					Required: true,
				},
				Validate: &parse.ValidateTag{
					Min: &[]int{18}[0],
					Max: &[]int{120}[0],
				},
			},
		},
	}

	bindCode, _ := GenerateBindFunction(structInfo)
	validateCode, _ := GenerateValidateFunction(structInfo)
	result := bindCode + validateCode

	expected := `// Code generated by go-wrangler. DO NOT EDIT.

func BindUser(r *http.Request, s *User) error {
	if val, err := strconv.Atoi(r.FormValue("Age")); err != nil {
		return fmt.Errorf("Age must be a valid integer")
	} else {
		s.Age = val
	}
	if r.FormValue("Age") == "" {
		return fmt.Errorf("Age is required")
	}
	return nil
}
// Code generated by go-wrangler. DO NOT EDIT.

func ValidateUser(s *User) error {
	if s.Age < 18 {
		return fmt.Errorf("Age must be at least 18")
	}
	if s.Age > 120 {
		return fmt.Errorf("Age must be at most 120")
	}
	return nil
}
`

	if result != expected {
		t.Errorf("TestGenerateFormWithValidation() = %v, want %v", result, expected)
	}
}
